### ISSUE TITLE
i can't run this thing locally

### ISSUE THREAD

**Issue by GarryTale** [raytran/protochess#11]
everytime is fine until "=> ERROR [builder 10/10] RUN npm run build"

------
 > [builder 10/10] RUN npm run build:
#14 0.605
#14 0.605 > svelte-app@1.0.0 build /usr/src/protochess/protochess-front
#14 0.605 > npm run routify -- -b && rollup -c
#14 0.605
#14 0.780
#14 0.780 > svelte-app@1.0.0 routify /usr/src/protochess/protochess-front
#14 0.780 > routify -D "-b"
#14 0.780
#14 0.958 [Routify] Generated routes in 0 ms
#14 1.209 [!] Error: Package subpath './compiler.js' is not defined by "exports" in /usr/src/protochess/protochess-front/node_modules/svelte/package.json
#14 1.209 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in /usr/src/protochess/protochess-front/node_modules/svelte/package.json
#14 1.209     at new NodeError (internal/errors.js:322:7)
#14 1.209     at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
#14 1.209     at packageExportsResolve (internal/modules/esm/resolve.js:565:3)
#14 1.209     at resolveExports (internal/modules/cjs/loader.js:478:36)
#14 1.209     at Function.Module._findPath (internal/modules/cjs/loader.js:518:31)
#14 1.209     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:917:27)
#14 1.209     at Function.Module._load (internal/modules/cjs/loader.js:774:27)
#14 1.209     at Module.require (internal/modules/cjs/loader.js:1003:19)
#14 1.209     at require (internal/modules/cjs/helpers.js:107:18)
#14 1.209     at Object.<anonymous> (/usr/src/protochess/protochess-front/node_modules/rollup-plugin-svelte/index.js:11:4)
#14 1.209
#14 1.215 npm ERR! code ELIFECYCLE
#14 1.216 npm ERR! errno 1
#14 1.220 npm ERR! svelte-app@1.0.0 build: `npm run routify -- -b && rollup -c`
#14 1.220 npm ERR! Exit status 1
#14 1.220 npm ERR!
#14 1.221 npm ERR! Failed at the svelte-app@1.0.0 build script.
#14 1.221 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#14 1.225
#14 1.225 npm ERR! A complete log of this run can be found in:
#14 1.225 npm ERR!     /root/.npm/_logs/2023-04-11T18_04_40_816Z-debug.log
------
executor failed running [/bin/sh -c npm run build]: exit code: 1

**Comment by ianfab** [comment]
I encountered the same a few days ago. See #10 for my suggested fix.

Edit: The PR has just been merged, so you can close the issue if works for you now as well.

**Comment by GarryTale** [comment]
alright, thanks
